services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v1
    restart: unless-stopped
    env_file: stack.env
    volumes:
      - "/mnt/storage/containers/service-data/pocket-id/volumes/data:/app/data"
      - "/mnt/storage/containers/service-data/pocket-id/volumes/secrets:/secrets:ro"
    # Optional healthcheck
    networks:
      - evilnet
    healthcheck:
      test: ["CMD", "/app/pocket-id", "healthcheck"]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=evilnet"
      - "traefik.http.routers.pocket-id.rule=Host(`id.evilwoods.net`)"
      - "traefik.http.routers.pocket-id.entrypoints=websecure"
      - "traefik.http.routers.pocket-id.tls.certresolver=letsencrypt"
      - "traefik.http.services.pocket-id.loadbalancer.server.port=1411"

networks:
  evilnet:
    external: true
