entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls: {}

certificatesResolvers:
  letsencrypt:
    acme:
      email: ""
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - 1.1.1.1:53
          - 8.8.8.8:53

providers:
  file:
    filename: "/dynamic/tls.yaml"
  docker:
    exposedByDefault: false
    network: evilnet

api:
  dashboard: true
  insecure: false
