services:
  tasktrove:
    image: ghcr.io/dohsimpson/tasktrove:latest
    container_name: tasktrove
    expose:
      - 3000
    volumes:
      - /mnt/storage/containers/service-data/task-trove/volumes/data:/app/data
    restart: unless-stopped
    networks:
      - evilnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tasktrove.rule=Host(`tasks.evilwoods.net`)"
      - "traefik.http.routers.tasktrove.entrypoints=websecure"
      - "traefik.http.routers.tasktrove.tls.certresolver=letsencrypt"
      - "traefik.http.routers.tasktrove.tls.domains[0].main=evilwoods.net"
      - "traefik.http.routers.tasktrove.tls.domains[0].sans=*.evilwoods.net"
      - "traefik.http.services.tasktrove.loadbalancer.server.port=3000"

networks:
  evilnet:
    external: true
